def Eng(self):
    self.l_comport.setText("COM Port")
    self.l_baudrate.setText("Baud Rate")
    self.l_parity.setText("Parity")
    self.l_stopbits.setText("Stop Bits")
    self.l_databit.setText("Data Bits")
    self.l_dt1.setText("Delay Time (ms)")
    self.serBtn.setText("Connect")
    self.TypeTab.setTabText(self.TypeTab.indexOf(self.serialTab), "Serial")
    self.l_ip.setText("　IP")
    self.l_port.setText("　Port")
    self.l_dt2.setText("Delay Time (ms)")
    self.etherBtn.setText("Connect")
    self.TypeTab.setTabText(self.TypeTab.indexOf(self.etherTab), "Ethernet")
    self.TypeBox.setTitle("Communication Type")
    self.codeBox.setTitle("Reserved Command")
    self.l_addr.setText("Address")
    self.label.setText("Fuction Code")
    self.CommBox.setTitle("Communtication Data")
    self.TxLabel.setText("Tx Window ")
    self.RxLabel.setText("Rx Window")
    self.groupBox.setTitle("Send Data")
    self.loop_inBtn.setText("Input")
    self.stopBtn.setText("STOP")
    self.singleBtn.setText("Single")
    self.loopBtn.setText("Loop")
    self.TxClearBtn.setText("Clear")
    self.saveBtn.setText("Save File")
    self.single_inBtn.setText("Input")
    self.langBox.setTitle("Language")
    self.korBtn.setText("Korean")
    self.engBtn.setText("English")


def Kor(self):
    self.l_comport.setText("통신 포트")
    self.l_baudrate.setText("통신 속도")
    self.l_parity.setText("패리티")
    self.l_stopbits.setText("스탑 비트")
    self.l_databit.setText("데이터 길이")
    self.l_dt1.setText("수신 지연시간 (ms)")
    self.serBtn.setText("연결")
    self.TypeTab.setTabText(self.TypeTab.indexOf(self.serialTab), "시리얼")
    self.l_ip.setText("　아이피")
    self.l_port.setText("　포트")
    self.l_dt2.setText("수신 지연시간 (ms)")
    self.etherBtn.setText("연결")
    self.TypeTab.setTabText(self.TypeTab.indexOf(self.etherTab), "이더넷")
    self.TypeBox.setTitle("통신 타입")
    self.codeBox.setTitle("예약 명령어")
    self.l_addr.setText("통신주소")
    self.label.setText("기능 코드")
    self.CommBox.setTitle("통신 데이터")
    self.TxLabel.setText("송신창")
    self.RxLabel.setText("수신창")
    self.groupBox.setTitle("입력 데이터")
    self.loop_inBtn.setText("입력")
    self.stopBtn.setText("정지")
    self.singleBtn.setText("단일실행")
    self.loopBtn.setText("반복실행")
    self.TxClearBtn.setText("전체 삭제")
    self.saveBtn.setText("파일로 저장")
    self.single_inBtn.setText("입력")
    self.langBox.setTitle("언어")
    self.korBtn.setText("한국어")
    self.engBtn.setText("영어")